apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-app
  namespace: ecommerce
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node-app
                port:
                  number: 80
  # Uncomment if you have cert-manager with a ClusterIssuer
  # tls:
  #   - hosts: ["api.example.com"]
  #     secretName: node-app-tls
