apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ecommerce
type: Opaque
data:
  jwt-secret: bXlzZWNyZXRrZXk=
  db-uri: bW9uZ29kYitzcnY6Ly9vbmV2emF0dGFsaGE6eVJQUjV0WjN0NjF2VmhtdEBzaW1wbGUtYmFja2VuZC5qZDl5ZTVhLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1zaW1wbGUtYmFja2VuZA==