apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          # Build & push your image, then put it here:
          image: ghcr.io/youruser/your-node-app:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: node-app-config
                  key: PORT
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: node-app-config
                  key: MONGO_DB
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-auth
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-auth
                  key: password
            # Compose a MONGO_URL from the vars above
            - name: MONGO_URL
              value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongo:27017/$(MONGO_DB)?authSource=admin"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
